# Generated by Django 3.1.4 on 2022-06-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portal', '0002_message_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
